version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./:/usr/app
    command: npm run start